import React, { useState, useEffect, useCallback } from 'react';
import { Calendar, BarChart2, TrendingUp, Filter, Download, RefreshCw, ChevronDown, Truck, User } from 'lucide-react';
import { useCompanyData } from '../../hooks/useCompanyData';
import { supabase } from '../../lib/supabase';
import toast from 'react-hot-toast';
import { useDateRange } from '../../hooks/useDateRange';
import PeriodSelector from '../../components/hodometros/PeriodSelector';
import LoadingSpinner from '../../components/LoadingSpinner';
import RVisualizationEmbed from '../../components/RVisualizationEmbed';

interface MonthlyData {
  month: string;
  km: number;
  driverData: {
    [driverId: string]: {
      name: string;
      km: number;
    }
  }
}

interface DriverSummary {
  id: number;
  name: string;
  totalKm: number;
  avgKmPerMonth: number;
  vehicles: string[];
  color: string;
}

const HodometrosDashboard = () => {
  const { query, companyId } = useCompanyData();
  const [loading, setLoading] = useState(true);
  const [monthlyData, setMonthlyData] = useState<MonthlyData[]>([]);
  const [driverSummaries, setDriverSummaries] = useState<DriverSummary[]>([]);
  const [selectedDrivers, setSelectedDrivers] = useState<number[]>([]);
  const [showDriverSelector, setShowDriverSelector] = useState(false);
  const { periodType, dateRange, updatePeriod, setDateRange } = useDateRange('6months');
  const [visualizationLoading, setVisualizationLoading] = useState(false);
  
  // Sample visualization paths - in a real implementation, these would be generated by the R script
  const [visualizationPaths, setVisualizationPaths] = useState({
    line: '/visualizations/driver_mileage_plot.png',
    changes: '/visualizations/driver_mileage_changes.png',
    interactive: '/visualizations/driver_mileage_interactive.html',
    data: '/visualizations/driver_mileage_data.csv'
  });

  // Color palette for drivers
  const colorPalette = [
    '#4e79a7', '#f28e2c', '#e15759', '#76b7b2', '#59a14f',
    '#edc949', '#af7aa1', '#ff9da7', '#9c755f', '#bab0ab'
  ];

  const fetchData = useCallback(async () => {
    try {
      setLoading(true);
      
      const { data, error } = await supabase
        .from('hodometro')
        .select(`
          *,
          motorista:motorista_id (
            motorista_id,
            nome,
            cpf
          ),
          veiculo:veiculo_id (
            veiculo_id,
            placa,
            marca,
            tipo
          ),
          cliente:cliente_id (
            cliente_id,
            nome
          )
        `)
        .eq('company_id', companyId)
        .gte('data', dateRange.startDate)
        .lte('data', dateRange.endDate)
        .order('data', { ascending: true });

      if (error) throw error;

      // Process monthly data
      processMonthlyData(data || []);
      
      // Process driver summaries
      processDriverSummaries(data || []);
      
      // Simulate refreshing visualizations
      simulateVisualizationRefresh();
      
    } catch (error) {
      console.error('Error fetching dashboard data:', error);
      toast.error('Erro ao carregar dados do dashboard');
    } finally {
      setLoading(false);
    }
  }, [companyId, dateRange]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const processMonthlyData = (data: any[]) => {
    // Group by month and driver
    const monthlyMap: Record<string, MonthlyData> = {};
    
    data.forEach(hodometro => {
      if (!hodometro.motorista) return;
      
      // Extract year and month
      const date = new Date(hodometro.data);
      const monthKey = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
      const monthName = date.toLocaleDateString('pt-BR', { month: 'short', year: 'numeric' });
      
      // Initialize month if not exists
      if (!monthlyMap[monthKey]) {
        monthlyMap[monthKey] = {
          month: monthName,
          km: 0,
          driverData: {}
        };
      }
      
      // Initialize driver if not exists
      const driverId = hodometro.motorista_id.toString();
      if (!monthlyMap[monthKey].driverData[driverId]) {
        monthlyMap[monthKey].driverData[driverId] = {
          name: hodometro.motorista.nome,
          km: 0
        };
      }
      
      // Add kilometers
      const km = hodometro.km_rodado || 0;
      monthlyMap[monthKey].km += km;
      monthlyMap[monthKey].driverData[driverId].km += km;
    });
    
    // Convert to array and sort by month
    const monthlyArray = Object.entries(monthlyMap).map(([key, value]) => ({
      ...value,
      monthKey: key
    })).sort((a, b) => a.monthKey.localeCompare(b.monthKey));
    
    setMonthlyData(monthlyArray);
  };

  const processDriverSummaries = (data: any[]) => {
    // Group by driver
    const driverMap: Record<string, any> = {};
    
    data.forEach(hodometro => {
      if (!hodometro.motorista) return;
      
      const driverId = hodometro.motorista_id.toString();
      
      // Initialize driver if not exists
      if (!driverMap[driverId]) {
        driverMap[driverId] = {
          id: hodometro.motorista_id,
          name: hodometro.motorista.nome,
          totalKm: 0,
          readings: 0,
          vehicles: new Set<string>()
        };
      }
      
      // Add kilometers and increment readings count
      driverMap[driverId].totalKm += hodometro.km_rodado || 0;
      driverMap[driverId].readings += 1;
      
      // Add vehicle
      if (hodometro.veiculo) {
        driverMap[driverId].vehicles.add(hodometro.veiculo.placa.toUpperCase());
      }
    });
    
    // Calculate months in the date range
    const startDate = new Date(dateRange.startDate);
    const endDate = new Date(dateRange.endDate);
    const monthsDiff = (endDate.getFullYear() - startDate.getFullYear()) * 12 + 
                       (endDate.getMonth() - startDate.getMonth()) + 1;
    
    // Convert to array, calculate averages, and sort by total km
    const driverSummaries = Object.values(driverMap).map((driver: any, index) => ({
      id: driver.id,
      name: driver.name,
      totalKm: driver.totalKm,
      avgKmPerMonth: monthsDiff > 0 ? Math.round(driver.totalKm / monthsDiff) : driver.totalKm,
      vehicles: Array.from(driver.vehicles),
      color: colorPalette[index % colorPalette.length]
    })).sort((a: any, b: any) => b.totalKm - a.totalKm);
    
    setDriverSummaries(driverSummaries);
    
    // Select top 5 drivers by default
    setSelectedDrivers(driverSummaries.slice(0, 5).map(d => d.id));
  };

  const simulateVisualizationRefresh = () => {
    setVisualizationLoading(true);
    
    // Simulate a delay for visualization generation
    setTimeout(() => {
      // In a real implementation, this would call the R script and update the paths
      setVisualizationPaths({
        line: `/visualizations/driver_mileage_plot.png?t=${Date.now()}`,
        changes: `/visualizations/driver_mileage_changes.png?t=${Date.now()}`,
        interactive: `/visualizations/driver_mileage_interactive.html?t=${Date.now()}`,
        data: `/visualizations/driver_mileage_data.csv?t=${Date.now()}`
      });
      
      setVisualizationLoading(false);
    }, 1500);
  };

  const toggleDriverSelection = (driverId: number) => {
    setSelectedDrivers(prev => {
      if (prev.includes(driverId)) {
        return prev.filter(id => id !== driverId);
      } else {
        return [...prev, driverId];
      }
    });
  };

  const selectAllDrivers = () => {
    setSelectedDrivers(driverSummaries.map(d => d.id));
  };

  const deselectAllDrivers = () => {
    setSelectedDrivers([]);
  };

  if (loading) {
    return <LoadingSpinner />;
  }

  return (
    <div className="space-y-6">
      {/* Filters Section */}
      <div className="bg-white dark:bg-gray-800 p-4 rounded-xl shadow-md border border-gray-200 dark:border-gray-700">
        <div className="flex flex-col md:flex-row justify-between gap-4">
          {/* Period Selector */}
          <div className="flex-1">
            <PeriodSelector
              periodType={periodType}
              dateRange={dateRange}
              onPeriodChange={updatePeriod}
              onDateRangeChange={setDateRange}
            />
          </div>
          
          {/* Driver Selector */}
          <div className="relative">
            <button
              onClick={() => setShowDriverSelector(!showDriverSelector)}
              className="px-4 py-2 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-colors flex items-center gap-2"
            >
              <User className="w-5 h-5 text-gray-400" />
              {selectedDrivers.length} Motoristas Selecionados
              <ChevronDown className="w-4 h-4 ml-1" />
            </button>
            
            {showDriverSelector && (
              <div className="absolute right-0 mt-2 w-72 bg-white dark:bg-gray-800 rounded-lg shadow-lg z-10 border border-gray-200 dark:border-gray-700">
                <div className="p-3 border-b border-gray-200 dark:border-gray-700 flex justify-between items-center">
                  <h4 className="text-sm font-medium text-gray-900 dark:text-white">Selecionar Motoristas</h4>
                  <div className="flex gap-2">
                    <button
                      onClick={selectAllDrivers}
                      className="text-xs text-blue-600 dark:text-blue-400 hover:underline"
                    >
                      Todos
                    </button>
                    <button
                      onClick={deselectAllDrivers}
                      className="text-xs text-gray-500 dark:text-gray-400 hover:underline"
                    >
                      Nenhum
                    </button>
                  </div>
                </div>
                <div className="p-2 max-h-60 overflow-y-auto">
                  {driverSummaries.map(driver => (
                    <div key={driver.id} className="flex items-center p-2 hover:bg-gray-50 dark:hover:bg-gray-700 rounded-md">
                      <input
                        type="checkbox"
                        id={`driver-${driver.id}`}
                        checked={selectedDrivers.includes(driver.id)}
                        onChange={() => toggleDriverSelection(driver.id)}
                        className="rounded border-gray-300 text-blue-600 focus:ring-blue-500 mr-3"
                      />
                      <label htmlFor={`driver-${driver.id}`} className="flex items-center cursor-pointer flex-1">
                        <div className="w-3 h-3 rounded-full mr-2" style={{ backgroundColor: driver.color }}></div>
                        <span className="text-sm text-gray-900 dark:text-white">{driver.name}</span>
                      </label>
                      <span className="text-xs text-gray-500 dark:text-gray-400">
                        {driver.totalKm.toLocaleString('pt-BR')} km
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Visualizations */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Monthly Mileage Line Chart */}
        <RVisualizationEmbed
          visualizationType="line"
          title="Quilometragem Mensal por Motorista"
          description="Visualização da quilometragem mensal de cada motorista ao longo do tempo"
          imagePath={visualizationPaths.line}
          isLoading={visualizationLoading}
          dateRange={dateRange}
          onDateRangeChange={setDateRange}
          onRefresh={simulateVisualizationRefresh}
          downloadOptions={{
            pngUrl: visualizationPaths.line,
            csvUrl: visualizationPaths.data,
            pdfUrl: visualizationPaths.line.replace('.png', '.pdf')
          }}
          className="lg:col-span-2"
        />
        
        {/* Significant Changes Visualization */}
        <RVisualizationEmbed
          visualizationType="changes"
          title="Mudanças Significativas na Quilometragem"
          description="Destaque de mudanças significativas na quilometragem mensal"
          imagePath={visualizationPaths.changes}
          isLoading={visualizationLoading}
          downloadOptions={{
            pngUrl: visualizationPaths.changes,
            pdfUrl: visualizationPaths.changes.replace('.png', '.pdf')
          }}
        />
        
        {/* Interactive Visualization */}
        <RVisualizationEmbed
          visualizationType="interactive"
          title="Visualização Interativa"
          description="Explore os dados de quilometragem com controles interativos"
          htmlPath={visualizationPaths.interactive}
          isLoading={visualizationLoading}
          downloadOptions={{
            csvUrl: visualizationPaths.data
          }}
        />
      </div>

      {/* Driver Summaries */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md border border-gray-200 dark:border-gray-700 overflow-hidden">
        <div className="p-4 border-b border-gray-200 dark:border-gray-700">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white flex items-center gap-2">
            <Truck className="w-5 h-5 text-blue-500 dark:text-blue-400" />
            Resumo por Motorista
          </h3>
        </div>
        
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
            <thead className="bg-gray-50 dark:bg-gray-800">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Motorista</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Veículos</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">KM Total</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Média Mensal</th>
              </tr>
            </thead>
            <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
              {driverSummaries.map((driver) => (
                <tr key={driver.id} className="hover:bg-gray-50 dark:hover:bg-gray-700/50">
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="w-3 h-3 rounded-full mr-2" style={{ backgroundColor: driver.color }}></div>
                      <div className="text-sm font-medium text-gray-900 dark:text-white">{driver.name}</div>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex flex-wrap gap-1">
                      {driver.vehicles.map((vehicle, index) => (
                        <span 
                          key={index} 
                          className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800 dark:bg-blue-900/20 dark:text-blue-200"
                        >
                          {vehicle}
                        </span>
                      ))}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-right">
                    <div className="text-sm font-medium text-gray-900 dark:text-white">
                      {driver.totalKm.toLocaleString('pt-BR')} km
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-right">
                    <div className="text-sm font-medium text-gray-900 dark:text-white">
                      {driver.avgKmPerMonth.toLocaleString('pt-BR')} km
                    </div>
                  </td>
                </tr>
              ))}
              
              {driverSummaries.length === 0 && (
                <tr>
                  <td colSpan={4} className="px-6 py-4 text-center text-sm text-gray-500 dark:text-gray-400">
                    Nenhum dado disponível para o período selecionado
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default HodometrosDashboard;