create table public.operacao_autoservice (
  id bigint generated by default as identity not null,
  id_viagem bigint not null,
  origem text null,
  destino text null,
  placa_veiculo text null,
  embarque text null,
  nome_cliente text null,
  tel_cliente smallint null,
  valor_frete text null,
  destino_final text null,
  constraint operacao_autoservice_pkey primary key (id),
  constraint operacao_autoservice_id_viagem_fkey foreign KEY (id_viagem) references acompanhamento_viagem (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.operacao_cesari (
  id bigint generated by default as identity not null,
  id_viagem bigint not null,
  origem text null,
  destino text null,
  nr_manifesto text null,
  ft_manifesto text null,
  v2_dt_hora timestamp without time zone null,
  v2_origem text null,
  v2_desitno text null,
  v2_capacidade smallint null,
  v2_nr_manifesto text null,
  v2_ft_manifesto text null,
  pernoite boolean null,
  dia_nao_util boolean null,
  tipo_viagem text null,
  constraint operacao_cesari_pkey primary key (id),
  constraint operacao_cesari_id_viagem_fkey foreign KEY (id_viagem) references acompanhamento_viagem (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.operacao_mitsubishi (
  id_operacao bigint generated by default as identity not null,
  id_viagem bigint null,
  origem text null,
  destino text null,
  frota text null,
  tipo_carreta smallint null,
  qtd_carro integer null,
  modelo_carro text null,
  km_chegada_porto text null,
  data_hora_chegada_porto timestamp without time zone null,
  constraint operacao_mitsubishi_pkey primary key (id_operacao),
  constraint operacao_mitsubishi_id_viagem_fkey foreign KEY (id_viagem) references acompanhamento_viagem (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.operacao_sada (
  id_operacao bigint generated by default as identity not null,
  id_viagem bigint null,
  origem text null,
  destino text null,
  tipo_carreta smallint null,
  tipo_carga text null,
  frota text null,
  nr_viagem text null,
  qtd_carros smallint null,
  modelo text null,
  destino2 text null,
  constraint operacao_sada_pkey primary key (id_operacao),
  constraint operacao_sada_id_viagem_fkey foreign KEY (id_viagem) references acompanhamento_viagem (id)
) TABLESPACE pg_default;

create table public.operacao_superterminais (
  id_operacao bigint generated by default as identity not null,
  id_viagem bigint null,
  embarque_desembarque smallint null,
  nome_container text null,
  capacidade smallint null,
  nr_container text null,
  ft_tablet text null,
  fim_de_semana boolean null,
  constraint operacao_superterminais_pkey primary key (id_operacao),
  constraint operacao_superterminais_id_viagem_fkey foreign KEY (id_viagem) references acompanhamento_viagem (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.operacao_tegma (
  id bigint generated by default as identity not null,
  id_viagem bigint not null,
  tipo_viagem text null,
  placa_carreta text null,
  nr_cautela text null,
  ft_cautela text null,
  origem text null default ''::text,
  foto_viagem text null,
  nr_viagem text null,
  p2_origem text null,
  p2_destino text null,
  p2_placa_veiculo text null,
  retorno boolean null,
  veiculo_transportado text null,
  empresa text null,
  qtd_carros integer null,
  destino text null,
  p2_nr_cautela text null,
  p2_ft_cautela text null,
  placa_veiculo_transportado text null,
  p2_data_hora timestamp without time zone null,
  constraint operacao_tegma_pkey primary key (id),
  constraint operacao_tegma_id_viagem_fkey foreign KEY (id_viagem) references acompanhamento_viagem (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.acompanhamento_viagem (
  id bigint generated by default as identity not null,
  data_hora_inicial timestamp without time zone not null,
  km_inicial text null,
  motorista_id bigint null,
  ajudante_id bigint null,
  veiculo_id bigint null,
  km_final text null,
  data_hora_final timestamp without time zone null,
  janta boolean null,
  cliente_id bigint null,
  hora_janta text null,
  constraint acompanhamento_viagem_pkey primary key (id),
  constraint acompanhamento_viagem_ajudante_id_fkey foreign KEY (ajudante_id) references documento_ajudante (id_ajudante),
  constraint acompanhamento_viagem_cliente_id_fkey foreign KEY (cliente_id) references cliente (cliente_id) on update CASCADE on delete set null,
  constraint acompanhamento_viagem_motorista_id_fkey foreign KEY (motorista_id) references motorista (motorista_id) on update CASCADE on delete CASCADE,
  constraint acompanhamento_viagem_veiculo_id_fkey foreign KEY (veiculo_id) references veiculo (veiculo_id)
) TABLESPACE pg_default;