-- =====================================================
-- Histórico de observações por BV (JPD Transportes)
-- Substitui a coluna única jpd_fretes.observacao (que fica
-- mantida só para compatibilidade, mas deixa de ser usada
-- pelo frontend) por um histórico empilhado: várias
-- observações por BV, cada uma com autor implícito por data.
-- =====================================================

CREATE TABLE IF NOT EXISTS public.jpd_frete_observacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  frete_id INTEGER NOT NULL REFERENCES public.jpd_fretes(id) ON DELETE CASCADE,
  observacao TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_jpd_frete_observacoes_frete_id
  ON public.jpd_frete_observacoes(frete_id, created_at DESC);

ALTER TABLE public.jpd_frete_observacoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON public.jpd_frete_observacoes;
CREATE POLICY "Enable read access for all users"
  ON public.jpd_frete_observacoes FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Enable insert for all users" ON public.jpd_frete_observacoes;
CREATE POLICY "Enable insert for all users"
  ON public.jpd_frete_observacoes FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Enable update for all users" ON public.jpd_frete_observacoes;
CREATE POLICY "Enable update for all users"
  ON public.jpd_frete_observacoes FOR UPDATE
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Enable delete for all users" ON public.jpd_frete_observacoes;
CREATE POLICY "Enable delete for all users"
  ON public.jpd_frete_observacoes FOR DELETE
  USING (true);
