/*
  # Create motorista_eventos_cliente table for tracking integration and training events

  1. New Table
    - Create motorista_eventos_cliente table to track integration and training events
    - Add columns for integration and training status and dates
    - Set up foreign key relationship with motorista table
    
  2. Purpose
    - Track integration and training status for contracted drivers
    - Store dates when integration and training were completed
    - Support filtering and reporting on driver onboarding status
*/

-- Create the motorista_eventos_cliente table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.motorista_eventos_cliente (
  id bigint generated by default as identity not null,
  motorista_id bigint null,
  integracao boolean null,
  integracao_data date null,
  treinamento boolean null,
  treinamento_data date null,
  constraint motorista_eventos_cliente_pkey primary key (id),
  constraint motorista_eventos_cliente_motorista_id_fkey foreign KEY (motorista_id) references motorista (motorista_id) on update CASCADE on delete set null
) TABLESPACE pg_default;

-- Add indexes for faster querying
CREATE INDEX IF NOT EXISTS idx_motorista_eventos_cliente_motorista_id 
ON public.motorista_eventos_cliente(motorista_id);

-- Add comment explaining the purpose of this table
COMMENT ON TABLE public.motorista_eventos_cliente IS 'Stores integration and training events for contracted drivers';